### ISSUE TITLE
fix dendrometer bands with double springs

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/Dendrobands#106]
@jess-shue , These are the two point dendrometer trees with double springs on the dendrometer bands, which we agreed yesterday that we'd like to fix:

tag | treeID | stemID | sp | dbh.2018.mm
-- | -- | -- | -- | --
190413 | 28001 | 28001 | litu | 1015
100771 | 12422 | 12422 | quru | 960

**Comment by rudeboybert** [comment]
1. @jess-shue I've added these two stems to [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv)
2. I've manually updated the [Google Sheet](https://docs.google.com/spreadsheets/d/1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588/edit#gid=1289938519) with these two (biweekly) stems

**Comment by rudeboybert** [comment]
Note we added `BA` code to `codes_metadata.csv` here: ca4f70f3234c0054d829af6fb50cfbc029687ac6

**Comment by rudeboybert** [comment]
Done in [data_entry_fix_2022-01.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2022/data_entry_fix_2022-01.csv), closed by #114
