### ISSUE TITLE
new dendroband not on list (tag 111305)

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/Dendrobands#109]
@jess-shue ,

Yesterday I found one of the new dendrobands (installed a couple weeks ago) in section 3, but could not find it on the speadsheet. 

Tag 111305, measurement: 5.85

**Comment by jess-shue** [comment]
@teixeirak  Thanks! I will add that data to the compiled datasheet. It was recorded as being in area 2, so it wouldn't have been listed on the sheet filtered for area 3. I think there are a few other 'area' adjustments we can do to make things a little easier - there were also some trees in section 2 that would make more sense to be in section 3. 
I know @rudeboybert had asked me about this before he finished making the new spreadsheet, so we'll have to think about it some more!

**Comment by rudeboybert** [comment]
Closed by 8d776bbf1884ca2bce3da48dcd08e1bcf7705fb8
