### ISSUE TITLE
measurements of dendrobands not on list

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/Dendrobands#110]
I believe these are trees that have been removed from the census, but noting here just in case:

131232 : 120.97
Tag in section 3 ending 1227 (partially buried): 121.95

We can close this issue after verifying that we have all the expected measurements.

**Comment by rudeboybert** [comment]
Correct, both of these stems are going to be dropped as indicated in [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv)
```
     tag stemtag sp    quadrat   dbh dbh18 action                                                tag_stemtag
   <dbl>   <dbl> <chr>   <dbl> <dbl> <dbl> <chr>                                                 <chr>      
1 131227       1 litu     1313  525.   556 retrieve band: band issue, stem dropped from database 131227-1   
2 131232       1 litu     1313  431.   440 retrieve band: band issue, stem dropped from database 131232-1 
```
