### ISSUE TITLE
where can I find 2022 & 2023 fall dendro survey data?

### ISSUE THREAD

**Issue by jenajordan** [SCBI-ForestGEO/Dendrobands#128]
@teixeirak  @ValentineHerr  - could you direct me to the fall annual dendro survey data? When I look in this repository under data, I seem to only be finding the biweekly data.  Thanks.

**Comment by jenajordan** [comment]
@teixeirak @ValentineHerr  - Ah, please ignore, unless I have this wrong…. It looks like it is merged w/ the biweekly data into a  “master file” for that year.

**Comment by jenajordan** [comment]
@jess-shue @teixeirak - actually, I see that for 2022 the fall dendro survey is included in the 'master file', but for 2023 I don't see the annual fall dendro survey in the 'master file'. any idea where I can find the latter?

**Comment by jenajordan** [comment]
@jess-shue  - would you have time on Monday for a brief phone call? I am trying to figure out as well the fall biannual census final DBHs for 2021-23. It seems that the DBH column value doesn't change through the year as tree grows?

**Comment by teixeirak** [comment]
@jenajordan , correct that DBH isn't updated. You'll calculate *circumference* growth as the difference between the measures. You can then calculate diameter growth using basic geometry. There is also a modest correction for curvature of the dendroband, but I don't have the reference/ link offhand.  You can add that later.

**Comment by jess-shue** [comment]
@jenajordan 
There are a few R scripts that may be helpful in this repository:  [growth_over_time](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/analysis/growth_over_time.R) and [convert_caliper_meas_to_dbh](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/analysis/convert_caliper_meas_to_dbh.R).

For the biannual measurements, they are in the [raw_data](https://github.com/SCBI-ForestGEO/Dendrobands/tree/master/resources/raw_data) folders by year. They are also merged into the [data](https://github.com/SCBI-ForestGEO/Dendrobands/tree/master/data) as the first and last survey.ID. Although, it looks like the fall 2023 biannual measurement may not have been merged - the survey.ID may need to be updated as it seems like the same ID was used for the final intraannual measurement.

**Comment by jenajordan** [comment]
@teixeirak @jess-shue  - thank you. This answers my questions.
