### ISSUE TITLE
Questions about Spring 2021 biannual survey data entry CSV

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/Dendrobands#48]
Hey @jess-shue, thanks for sending the `data_entry_biannual_spr2021.csv` data entry form by email back on 3/26. I pushed it to GitHub in 8c97082d80d84196fcaee2f6c5c2035bbf271014. I'm going to shortly merge these data to the master `data/scbi.dendroAll_2021.csv` file using Ian's script you pointed me to, but I have some questions first.

## Question 1
I noticed that for 104 stems (`tag` + `stemtag`), there are duplicate row entries of this sort:

|    tag| stemtag| new.band| measure|notes                                          |
|------:|-------:|--------:|-------:|:----------------------------------------------|
|  10469|       1|        1|   56.54|NA                                             |
|  10469|       1|        0|      NA|only one band                                  |
|  12259|       1|        1|   25.37|NA                                             |
|  12259|       1|        0|      NA|band removed                                   |
|  20587|       1|        1|   14.87|NA                                             |
|  20587|       1|        0|      NA|only one band                                  |
|  30462|       1|        1|    9.17|NA                                             |
|  30462|       1|        0|  135.91|band removed                                   |

The pattern being stems with new bands are appearing twice. In previous `data_entry_biannual_sprXXX.csv` years, such instances always appeared in one row, like in 2019

|    tag| stemtag| new.band| measure|notes                  |
|------:|-------:|--------:|-------:|:----------------------|
|  22170|       1|        1|   30.77|band adjusted          |
|  22333|       1|        1|   51.98|band adjusted          |
|  40941|       1|        1|  104.00|band adjusted          |

I'm guessing its ok to de-duplicate those rows and combine the new.band, measure, and notes variables appropriately. Before I do so, could you confirm that the above duplication wasn't intentional? If it was, could you let me know reasoning?

## Question 2
Of these 104 duplicated stems mentioned above, I noticed that 9 of them had slightly different new.band, measure, and notes behavior. 

|    tag| stemtag| new.band| measure|notes          |
|------:|-------:|--------:|-------:|:--------------|
|  22170|       1|        0|   37.95|NA             |
|  22170|       1|        0|      NA|only one band  |
|  70146|       1|        0|   11.05|NA             |
|  70146|       1|        0|      NA|only one band  |
| 111039|       1|        0|   16.51|NA             |
| 111039|       1|        0|      NA|only one band  |
| 112482|       1|        0|   10.72|NA             |
| 112482|       1|        0|      NA|only one band  |
| 121358|       1|        0|    6.51|NA             |
| 121358|       1|        0|      NA|only one band  |
| 132302|       1|        0|   32.58|NA             |
| 132302|       1|        0|      NA|only one band  |
| 132529|       1|        0|   25.24|NA             |
| 132529|       1|        0|  138.88|band removed   |
| 180235|       1|        0|   48.05|NA             |
| 180235|       1|        0|      NA|only one band  |
| 190067|       1|        0|   38.64|double-checked |
| 190067|       1|        0|      NA|only one band  |

In particular I'm wondering if there is a typo in the new.band value. Should we set new.band to 1 for these 9 stems and then deduplicate like in Question 1?

## Question 3
There were also 19 stems you surveyed that are not included in the new year `scbi.dendroAll_2021.csv` I get when I run the [`new_scbidendroAll_[YEAR].R`](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/survey_forms/new_scbidendroAll_%5BYEAR%5D.R) script per the [Workflow for fall dendroband biannual survey](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/workflow_fallbiannual_survey.md). They all seem to involve dead stems. Any idea why? If not, no biggie, I can ask Ian.

|    tag| stemtag| measure| new.band|codes |notes               |
|------:|-------:|-------:|--------:|:-----|:-------------------|
| 171314|       1|      NA|        0|DC    |NA                  |
| 111029|       1|      NA|        0|DC    |NA                  |
| 140756|       1|      NA|        0|DS    |NA                  |
|  50160|       1|   15.38|        0|DS    |NA                  |
|  60562|       1|    7.54|        0|DS    |NA                  |
|  80005|       1|   19.94|        0|DS    |NA                  |
|  22333|       1|   42.32|        0|DS    |NA                  |
|  92139|       1|   38.25|        0|DS    |NA                  |
| 112060|       1|   93.27|        0|DS    |NA                  |
| 112118|       1|   64.96|        0|DS;L  |NA                  |
| 122005|       1|  102.82|        0|DS    |NA                  |
| 132028|       1|   54.05|        0|DS    |EAB emergence holes |
| 141146|       1|   17.65|        0|DS;B  |NA                  |
| 142206|       1|   97.90|        0|DS    |NA                  |
| 172255|       1|  124.20|        0|DS    |NA                  |
| 190935|       1|      NA|        0|DC    |NA                  |
| 122452|       1|   64.40|        0|DS    |NA                  |
| 132525|       1|      NA|        0|DC    |NA                  |
| 192570|       1|      NA|        0|DS    |gap closed          |

**Comment by teixeirak** [comment]
I think we can close this.
