### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/Dendrobands#77]
And then link to Zenodo so we can get DOI

**Comment by teixeirak** [comment]
Done, although I still need to release this and SCBImortality on Zenodo.

**Comment by rudeboybert** [comment]
If you make me an owner of these two repos I'm happy to do it

**Comment by teixeirak** [comment]
I just did the release for both dendrobands and mortality. I decided to use calendar versioning for these. 

@rudeboybert , I'll let you go grab the DOIs from Zenodo, and would appreciate it if you could add them to the readmes while you're at it.
