### ISSUE TITLE
review trees died/removed from census

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/Dendrobands#81]
We need to ensure (1) that dead trees are removed from the census, and (2) that trees removed are really dead.

# notes from 2021 fall census:

From @jenajordan:

Of note - we happened upon trees with dendrobands that aren’t listed in the survey (and I assume there are more, as these were ones I/ Bill happened to come across). Furthermore @rudeboybert confirmed these 5 trees were not in database

172154 standing dead 
172626 Fram standing dead top broke
172587 Fram standing dead top broke
92006 37.99mm
92138 9.97mm

From Bill:

i would also mention there about 20 standing dead trees with dendrobands.  it is a struggle to reach many of those trees and life would be simpler if the bands were removed once the tree dies. 

# to do:
- [ ] check what happened with #92006 and #92138. Perhaps these were erroneously marked dead? Assuming these are live (right, @jenajordan ?), they should be returned to the census
- [ ]  remove all dead trees from census list
- [ ] physically remove bands from dead trees

**Comment by rudeboybert** [comment]
related to #87 and #88

**Comment by rudeboybert** [comment]
Superseded by #89
