### ISSUE TITLE
Sampling strategy for new bands

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/Dendrobands#97]
As discussed in today's meeting, @jess-shue needs @teixeirak to decide a sampling strategy for where to install new bands, ideally using the summaries from the 2021 season found in [`dendro_trees_sp_2021_min_max_mean_dbh.csv`](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/results/dendro_trees_dbhcount/dendro_trees_sp_2021_min_max_mean_dbh.csv). Topics discussed:

- Top-level criteria: at least 12 bands per species considering ordering of productivity (but not ash (dying), elm (lower priority), dogwood)
- Then move to proportionality: crown illumination
- No more litu's!
- Running Ian's script [`replace_dead_trees_dendrobands.R`](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/survey_forms/replace_dead_trees_dendrobands.R) which bases decision on ANPP
- Having a cap on the number of bands for each species
- Oaks

(On the topic of said annual summaries, in #94 I automated the recomputation of these annual summaries at every GitHub actions run. One could argue this only needs to be done after the fall biannual survey, but because the recomputation is so quick I figured why not at every run)

**Comment by rudeboybert** [comment]
Also consider following note from Krista:

On another note, I have 8 automated point dendrometers on the way! https://tomst.com/web/en/systems/tms/point-dendrometer/ I'm thinking about which trees should get them and wondering if you have any input as to what would be most useful for your work. Growth can be quite variable around the radius of a tree, so one could think of replicates on a single tree, by species, or by size class. I'd really like to include LITU (as dominant species), QUAL (2nd dominant), FAGR (a really interesting species), and maybe one other ring-porous species (another oak, or perhaps a Carya).

**Comment by rudeboybert** [comment]
Need this by March 2nd. Also look at maps, consider which trees that died and consider whether they were in the biweekly census

**Comment by teixeirak** [comment]
I've made [this file](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/planning/dendro_trees_sp_2021_min_max_mean_dbh_with_dominance.csv) as a first pass at planning/ prioritizing the new bands. 

If we want to get the top 10 most productive species (excluding FRAM) up to ≥12 bands each, this only requires installing 5 new bands (1 JUNI, 2 CATO, 2 CACO). The top 15 would require an additional 34, and the top 18 an additional 26.

I'd propose that we (1) don't allow n bands to drop below 500, and (2) work down this list in order of priority, and just see how far we can get.

**Comment by rudeboybert** [comment]
Thanks for posting that CSV. Recall in #89 we identified 52 dead stems and thus we need new stems for. Here is a summary of what is current and what I'm proposing:

&nbsp; | biannual | biweekly | total
--- | --- | --- | ---
Before removing 52 dead | 403 | 146 | 549
After removing 52 dead | 356 | 141 | 497 
Proposed database | 400 | 150 | 550
Needed new stems | 44 | 9 | 53 

I posted my suggested sampling strategy in this [CSV](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/planning/current_distribution.csv), but also below. I propose we distribute the

1. 44 new biannual down the priority list so that each sp has at least 12. i.e. Following `new_bian` down to 3 new `tiam`
2. 9 new biweekly down the priority list so that each sp has at least 2. i.e. Following `new_biwk` down to 1 new `caovl`

|sp    | group| bian| biwk| new_bian| total_new_bian| new_biwk| total_new_biwk|
|:-----|-----:|----:|----:|--------:|--------------:|--------:|--------------:|
|litu  |     1|  179|   43|        0|              0|        0|              0|
|qual  |     1|   27|   32|        0|              0|        0|              0|
|quru  |     1|   19|   33|        0|              0|        0|              0|
|quve  |     1|   31|    0|        0|              0|        2|              2|
|qupr  |     1|   12|    0|        0|              0|        2|              4|
|cagl  |     1|   26|    3|        0|              0|        0|              4|
|juni  |     1|   10|    1|        2|              2|        1|              5|
|cato  |     1|   10|    0|        2|              4|        2|              7|
|caco  |     1|    7|    1|        5|              9|        1|              8|
|fagr  |     1|    1|   12|       11|             20|        0|              8|
|caovl |     2|    3|    0|        9|             29|        1|              9|
|acru  |     2|    7|    0|        5|             34|        0|              9|
|ploc  |     2|    5|    0|        7|             41|        0|              9|
|tiam  |     2|    0|    1|       12|             53|        0|              9|
|nysy  |     2|    7|    1|        5|             58|        0|              9|
|ceca  |     3|    1|    0|       11|             69|        0|              9|
|pist  |     3|    6|    0|        6|             75|        0|              9|
|ulru  |     3|    3|    0|        9|             84|        0|              9|
|caca  |     4|    1|   13|       11|             95|        0|              9|
|cofl  |     4|    0|    1|       12|            107|        0|              9|
|fram  |     5|    1|    0|       11|            118|        0|              9|

**Comment by rudeboybert** [comment]
[Google sheet](https://docs.google.com/spreadsheets/d/1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588/edit#gid=1963733752) for Thu 2/24 meeting

**Comment by teixeirak** [comment]
@rudeboybert and @jess-shue , I've realized that it's probably better to have a continuous long-term record on individual trees that is a mix between biannual and biweekly than to have two shorter biannual + biweekly records on separate trees. That is, it's best if new biweekly trees are converted from biannual trees, and trees dropped from the biweekly survey are retained as biannual. So I've added columns to the spreadsheet indicating the numbers of trees that should shift between biannual and biweekly.

**Comment by teixeirak** [comment]
# strategy used for 2022 band replacements
- Get at least 4 biweekly bands on priority group 1-3 species (16 species, excluding ULRU and PLOC), which requires modest reductions in some over-sampled species. 
- bring all priority group 1 species up to 12+ biannual bands and all priority group 2-3 species to 8+ bands
- reband all trees with a biweekly record when needed, but allow shifts from biweekly to biannual to improve sampling scheme
- draw new biweekly records from the biannual pool

**Comment by rudeboybert** [comment]
Based on Krista's final "agonizing decisions" on the [Google Sheet](https://docs.google.com/spreadsheets/d/1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588/edit#gid=1289938519), I've written out a draft [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv) indicating which stems need rebanding, (tentative) new band installation, and old retrieving (b/c the stem has died), along with the variables you said you wanted. 

@teixeirak as well: I say "draft" b/c while the stems that need rebanding and old band retrieving are set, the stems that need new band installation are not. In the interest of getting you a draft ASAP, I sampled the number of trees needed completely at random, whereas ultimately I hope to sample the trees stratified by size. I made some exploratory plots to aid in this below. The histograms show the distribution of dbh based on the 2018 census and the vertical red lines indicate the dbh of the stems we currently have in the dendrobands database:

![biannual](https://user-images.githubusercontent.com/4574203/155799030-dc451f9a-8643-45e8-be78-7db7aaa531a0.png)
![biweekly](https://user-images.githubusercontent.com/4574203/155799031-c8a83c33-8fe2-4649-882a-05a93fe59934.png)

For example, according to the Google Sheet we need to sample 3 new `tiam` for the biweekly survey. I'm thinking we need a smaller one, a larger one, and perhaps another medium size one. 

I'm hoping to get a finalized version of [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv) with the  finalized stems to install new bands by Monday mid-afternoon. @jess-shue Let me know:

1. If the format of the draft is what you were envisioning
2. If you need the finalized action_item_list.csv earlier than Monday mid-afternoon
3. You'd like me to merge the [tag_issue.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/tag_issue.csv) in action_item_list.csv so you have only one CSV to consider
4. Also the answer to Krista's team's question: what is the minimal dbh a stem needs to be able to install a dendroband on

**Comment by jess-shue** [comment]
@rudeboybert 
1. This looks pretty good! Should I plan to make a datasheet that would match the current R code? I realize our process is much different this year than in the past, but we will need to include several other columns for data recording in the field.
2. That should be OK. 
3. I'm not sure I have time to make tags before next week. The tag checks might just wait until the biannual measurement to provide some more breathing room.
4. Just replied on Teams, but I tend to avoid banding stems <10 cm DBH as smaller trees tend to overgrow their bands more frequently requiring more replacements/repairs. But, for smaller statured species like 'ceca' it may sometimes be necessary and that's OK!

**Comment by rudeboybert** [comment]
@jess-shue by datasheet I'm assuming you mean the raw-data CSV's in `resources/raw_data/` where measurements are recorded? If so and you need it by Wed 3/2, I think it might be easiest to just manually hack one out based on the template [data_entry_biannual_spr2022_BLANK.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2022/data_entry_biannual_spr2022_BLANK.csv) file we have for now. We can worry about generating these automatically sometime between 3/2 and the first survey date of Tue 3/15.

**Comment by teixeirak** [comment]
We have new productivity rankings based on census 2-3 and allodb allometries (https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/issues/36). There is some movement of species, but our planned band installs are still appropriate. If it doesn't mess things up to change numbers of bands shifted between biweekly and biannual, I might tweak that, but it's fine as is.

<img width="133" alt="image" src="https://user-images.githubusercontent.com/6355854/155844593-3f7433c8-1873-4de9-a637-72ab8990a60b.png">

**Comment by jess-shue** [comment]
@rudeboybert I have some questions about the action items list. There are still some litu's on the list (110788, 160910), but not all of them. Were some to be kept and others not? I also had a qual >130 mm (112354) that is not listed as needing a new band...

I'm happy to ignore the list that I had previously made and just go with this list, but I just wanted to confirm.
Thanks!

**Comment by jess-shue** [comment]
> @jess-shue by datasheet I'm assuming you mean the raw-data CSV's in `resources/raw_data/` where measurements are recorded? If so and you need it by Wed 3/2, I think it might be easiest to just manually hack one out based on the template [data_entry_biannual_spr2022_BLANK.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2022/data_entry_biannual_spr2022_BLANK.csv) file we have for now. We can worry about generating these automatically sometime between 3/2 and the first survey date of Tue 3/15.

@rudeboybert Previously when repairing bands a file called "field_form_fix" would have been generated by the [`fix_dendrobands.R`](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/survey_forms/fix_dendrobands.R) code. This file includes columns that aren't used in the raw data entry form to record the tree's DBH, the diameter at the band, height of band installation, etc. 

Once you have a final list I'll plan to hack one as suggested.

**Comment by rudeboybert** [comment]
Update:

1. In the [Google sheet](https://docs.google.com/spreadsheets/d/1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588/edit#gid=1289938519) I've reordered the rows and updated the priority group to reflect the new allodb ANPP allometries. As you said, no band counts were changed.
2. @jess-shue Yes, there are litu's on the list to reband, but only the two biweekly and not the 14 biannual. The idea being that since biweekly bands yield so much information (per Cam's paper), we're VERY hesitant to throw them out, even if it means doing nothing to solve the imbalance in species representation. On the other hand, we're not going to reband the 3 caca given how low they are on the ANPP list/priority group.
3. Jess: Regarding qual 112354 (biannual), great catch! It's really great to have a pair of fresh 👀 sanity checking the outputs. I've highlighted the relevant qual values in yellow on the Google Sheet. We're not going to reband the 1 + 3 = 4 biannual quals (112354 is one of them). Furthermore, we're shifting 7 biweekly quals to be only measured biannually so as to preserve their valuable biweekly records. This is making me realize that I need to add a `retrieve band: band issue, stem dropped from database` action item to [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv) for all stems in columns K & L that are not going to be rebanded. 
4. Jess: sounds good about the `field_form_fix`. I realize that in a sense I've re-invented the wheel by not using [fix_dendrobands.R](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/survey_forms/fix_dendrobands.R), but that might be a good thing. We can use both results as sanity checks against each other. 

Today I'll lock down:
1. Finalizing the dbh stratified sampling of stems to install new bands
2. Adding the `retrieve band: band issue, stem dropped from database`

**Comment by rudeboybert** [comment]
Hey folks, I think we finally have what we need:

1. [Google sheet](https://docs.google.com/spreadsheets/d/1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588/edit#gid=1289938519): Note cells in yellow are bands that will not be replaced and thus the bands need to be retrieved
2. [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv) has three possible action items: install band on new stem (biweekly and biannual), reband a stem with an existing band, retrieve band (stem died or won't be replaced). The number of rows in each action item line up with the counts in the Google Sheet. 
3. [action_item_list_backup_stems.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list_backup_stems.csv) is a short list of backup stems in case any of the stems in [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv) don't work out.

@jess-shue Could you take a look and see if this is what you need? Also whatever independent sanity checks you could do on the selected stems would be much appreciated. 

Fingers crossed that this all works out!

**Comment by teixeirak** [comment]
Thank you so much, Bert!

Kristina J. Anderson-Teixeira
Ecologist, Leader of ForestGEO Ecosystems & Climate Program
Smithsonian Conservation Biology Institute & Smithsonian Tropical Research Institute
1-540-635-6546 | ***@***.******@***.***>
Address: Smithsonian Conservation Biology Institute
1500 Remount Rd. MRC 5535; Front Royal, VA 22630<webextlink://1500%20Remount%20Rd.%20MRC%205535;%20Front%20Royal,%20VA%2022630> USA
ForestGEO Ecosystems & Climate Program <https://forestgeo.si.edu/research-programs/ecosystems-and-climate-program>
Lab Website<https://sites.google.com/site/forestecoclimlab/home>


From: Albert Y. Kim ***@***.***>
Date: Monday, February 28, 2022 at 5:16 PM
To: SCBI-ForestGEO/Dendrobands ***@***.***>
Cc: Teixeira, Kristina A. ***@***.***>, Mention ***@***.***>
Subject: Re: [SCBI-ForestGEO/Dendrobands] Sampling strategy for new bands (Issue #97)
External Email - Exercise Caution

Hey folks, I think we finally have what we need:

  1.  Google sheet<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588%2Fedit%23gid%3D1289938519&data=04%7C01%7Cteixeirak%40si.edu%7Ca4f9061802954ada767d08d9fb07f8b3%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637816833922824615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c9lqunCyLAfMNAMyjNuDX3mDUFUSqzCfbvILMxHoHIw%3D&reserved=0>: Note cells in yellow are bands that will not be replaced and thus the bands need to be retrieved
  2.  action_item_list.csv<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCBI-ForestGEO%2FDendrobands%2Fblob%2Fmaster%2Fresources%2Fraw_data%2F2021%2Fidentifying_stems_with_issues%2Faction_item_list.csv&data=04%7C01%7Cteixeirak%40si.edu%7Ca4f9061802954ada767d08d9fb07f8b3%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637816833922824615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CaJB6fOO5WDg1JSl99tCg8q0iSIDVhbnYpaDve3I0jQ%3D&reserved=0> has three possible action items: install band on new stem (biweekly and biannual), reband a stem with an existing band, retrieve band (stem died or won't be replaced). The number of rows in each action item line up with the counts in the Google Sheet.
  3.  action_item_list_backup_stems.csv<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCBI-ForestGEO%2FDendrobands%2Fblob%2Fmaster%2Fresources%2Fraw_data%2F2021%2Fidentifying_stems_with_issues%2Faction_item_list_backup_stems.csv&data=04%7C01%7Cteixeirak%40si.edu%7Ca4f9061802954ada767d08d9fb07f8b3%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637816833922824615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UBWFhgFccBGwD2I8KHV%2Fj%2BvAq50SQCakuIGxcvp9X3U%3D&reserved=0> is a short list of backup stems in case any of the stems in action_item_list.csv<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCBI-ForestGEO%2FDendrobands%2Fblob%2Fmaster%2Fresources%2Fraw_data%2F2021%2Fidentifying_stems_with_issues%2Faction_item_list.csv&data=04%7C01%7Cteixeirak%40si.edu%7Ca4f9061802954ada767d08d9fb07f8b3%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637816833922824615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CaJB6fOO5WDg1JSl99tCg8q0iSIDVhbnYpaDve3I0jQ%3D&reserved=0> don't work out.

@jess-shue<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjess-shue&data=04%7C01%7Cteixeirak%40si.edu%7Ca4f9061802954ada767d08d9fb07f8b3%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637816833922824615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fE4SH5x2YEWlFVwafDdgzg9xY3Jd6yt%2F77TCAUHn3vg%3D&reserved=0> Could you take a look and see if this is what you need? Also whatever independent sanity checks you could do on the selected stems would be much appreciated.

Fingers crossed that this all works out!

**Comment by jess-shue** [comment]
Hi @rudeboybert,
   Things look good so far. My only concern is that I see several stems that are < 5 cm DBH per their 2018 DBH. `dbh18` is mm I believe. I wouldn't typically recommend banding trees that small. Are we going ahead with those bands?
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



tag | stemtag | sp | quadrat | dbh | dbh18 | action | built |  
-- | -- | -- | -- | -- | -- | -- | -- | --
191287 | 1 | caco | 1912 | NA | 12 | install band on new stem: biannual
121252 | 2 | ceca | 1208 | NA | 15 | install band on new stem: biweekly
153362 | 1 | ulru | 1510 | NA | 16 | install band on new stem: biannual
153308 | 1 | ceca | 1509 | NA | 17 | install band on new stem: biannual
70831 | 1 | ceca | 702 | NA | 18 | install band on new stem: biweekly
73008 | 1 | ulru | 702 | NA | 18 | install band on new stem: biannual
23458 | 1 | ulru | 203 | NA | 23 | install band on new stem: biannual
100549 | 1 | ceca | 1004 | NA | 26 | install band on new stem: biannual
80729 | 1 | cato | 811 | NA | 37 | install band on new stem: biannual
150841 | 2 | ceca | 1509 | NA | 38 | install band on new stem: biannual
101008 | 3 | tiam | 1006 | NA | 46 | install band on new stem: biweekly
143325 | 1 | ceca | 1407 | NA | 46 | install band on new stem: biweekly
172636 | 2 | ceca | 1732 | NA | 46 | install band on new stem: biannual
130693 | 1 | caco | 1306 | NA | 47 | install band on new stem: biannual



</body>

</html>

**Comment by rudeboybert** [comment]
oh no the cm vs mm units get me again! let me regenerate lists

**Comment by teixeirak** [comment]
We don't want bands that small.

**Comment by rudeboybert** [comment]
Hey @jess-shue fixed. BTW this is the second time I've mixed this up in an analysis 🤦🏼‍♂️ I'm going to add a post-it to my wall!

**Comment by jess-shue** [comment]
@rudeboybert  haha, it is so easy to do! I checked and double-checked to make sure I wasn't out of line!

**Comment by jess-shue** [comment]
@rudeboybert Quick summary of replacement work:
- 5 trees were dead, damaged, or otherwise unsuitable for band installation:  92140 (reband), 92520 (new) DN; 122017  (new) DS; 20572 (new), 190755 (new) damaged
- 3 trees didn't need their bands replaced:  190694 band adjusted but OK; 121305 new band installed 2021, removed original band; 102348 band OK

To-do:
- remove bands per the generated list (John and I did collect 5)
- install bands on 9 trees: 3 we didn't get to, 4 dead/damaged, along with Krista's 2 large trees and

**Comment by teixeirak** [comment]
> * 5 trees were dead, damaged, or otherwise unsuitable for band installation:  92140 (reband), 92520 (new) DN; 122017  (new) DS; 20572 (new), 190755 (new) damaged

This isn't a big deal, but one way to avoid in the future would be to look up the tree's status in the 2021 mort census. (I did this for the point dendrometers.)

**Comment by rudeboybert** [comment]
Thanks for the summary Jess. I'll:

1. Update [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv) (which in hindsight I should've called work_order.csv) to reclassify these 8 stems
2. Try as much as possible to cross-reference all stems with the mortality results first, so that only live stems get randomly sampled for new band installation.

I'm going to retroactively update the 92140 dead stem by setting it as DN in the Fall 2021 raw-data and add a `notes` indicating we did this.

**Comment by rudeboybert** [comment]
Hey @jess-shue that [data_entry_fix_2022.csv](https://github.com/SCBI-ForestGEO/Dendrobands/tree/master/resources/raw_data/2022) file looks great! It will prove essential for when we tackle #100 

As for the 5 stems you identified as dead, damaged, or otherwise unsuitable for band installation, and thus needed new stems for. At near the same time as your last post, I whipped up a second list of backup stems: [action_item_list_backup_stems_2.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list_backup_stems_2.csv). For each of the 5 stems, I sampled 5 similarly sized stems, making sure that they weren't marked as dead in the mortality database here: [allmort.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/data/allmort.csv). In other words, I would scrap the original backup list in favor of this new backup list b/c the chances of sampling a dead stem are much lower. 

On another note about 92140 (reband): would you say this was a dead stem (and thus we need to retroactively mark it as D in the 2021 Fall Biannual survey raw-data file)? I ask b/c it wasn't listed as dead in [allmort.csv](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/data/allmort.csv). I could be it was missed during the 2021 mortality census.

**Comment by jess-shue** [comment]
@rudeboybert  Let me check 92140 next week. Bill wasn't sure if it was gone, or if a tag was missing. His notes were less confident as to whether or not that tree was dead.

**Comment by rudeboybert** [comment]
Hey @jess-shue

## Update
In PR #108 based on the `make-2022-field-form` branch I've:

1. Resolved stems 190694 (adjusted), 121305, 102348 that don't need bands replaced and set 92140 as `codes = DN` (for now pending your check):
    1. Retroactively changed the `raw-data/` field forms
    2. Updated the [action_item_list.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2021/identifying_stems_with_issues/action_item_list.csv)
1. Made an updated version of the spring biannual form called `data_entry_biannual_spr2022_BLANK_version_2.csv`. Things are not quite there though:
    1. The form currently has 494 stems, whereas it should 500 (see below)
    2. Some stems have missing `area` values which need to be associated to the [dendroband_biannual_map.pdf](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/maps/dendroband_biannual_map.pdf) map you showed me. 

## A few heads up
That you might be on top of already (forgive me if so):

1. In the updated version of the spring biannual form `data_entry_biannual_spr2022_BLANK_version_2.csv`, for the new stems I set the `dbh` column to be `dbh18` from [data_entry_fix_2022.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2022/data_entry_fix_2022.csv). Please let me know if this is incorrect
1. In data_entry_fix_2022.csv, the stems below are still present. Please let me know when I can delete these (my scripts use this CSV file):
    1. The 3 stems that no longer need a new band 190694, 121305, 102348 
    2. Of the 5 stems you indicated are dead, damaged, or otherwise unsuitable (92140, 92520, 122017, 20572, 190755), the first two: 92140, 92520
2. There are four stems that are marked for band replacement in the updated action_item_list.csv that are not in data_entry_fix_2022.csv: 100771, 160910, 190413, 200586.  
Two of these were the double springed-stems in #106 (100771, 190413), but that still leaves 160910 and 200586 unaccounted for. 
4. I hunted down the source of the 494 vs 500 discrepancy of 6. They can be explained in this table, where "count should be" is from the [Google sheet](https://docs.google.com/spreadsheets/d/1rneieQOCclZ2q-Kbxog-rzNMM6-9d7foGooTv8Xq588/edit#gid=1289938519) and "count is" is from data_entry_fix_2022.csv

sp | count should be | count is | diff | stems
-- | -- | -- | -- | --
ceca | 7 | 5 | 2 | 92520, 122017
ulru | 5 | 3 | 2 | 20572, 170755
cato | 3 | 2 | 1 | 92140
juni | 1 | 0 | 1 | 180648

All but the juni are one of the 5 stems you indicated are dead. I'm hoping the "3 we didn't get to" stems you mentioned earlier are 160910 and 200586 from Point 3 above and the juni 180648 from Point 4 above. If so, then every stem is accounted for!

**Comment by jess-shue** [comment]
Hi @rudeboybert 
1. Sounds good
2. You can delete them; I had included them just for reference but OK to delete
3. I did not keep them in data_entry_fix because they hadn't been replaced yet - so no data for them. I have them in  field_form_fix file along with the double spring fixes.
4. Yes, those are in my datasheet mentioned in #3. 

Question:  if I find that 92140 (cato, reband stem) is dead not found as Bill stated, should I have a backup stem ready to replace it to keep our numbers?

**Comment by rudeboybert** [comment]
Hey @jess-shue I'm answering on the road so apologies if anything that I say doesn't make sense. I'll be at a computer later this afternoon 

1. Yes please have a backup in mind. I believe there should be 5 catos to choose from in the second backup list
1. If you can't find 182471 in the 2018 census please feel free to pick another ceca in the second backup list 
1. Question for you: what is the best way to associate areas to stems? Do you suggest using a script by Ian or just doing it manually using the map pdf?

**Comment by jess-shue** [comment]
1. Got it - thanks!
2. I'll be sure to look for it in the 20x20, just not sure why I couldn't find it! And I'll add a backup.
3. Starting at line 76 in [biannual_survey.R](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/survey_forms/biannual_survey.R) there is code to assign the area based on the grid location

**Comment by jess-shue** [comment]
@rudeboybert I caught an omission! 160910 was re-banded on 3/2/2022 - the data had been recorded on a third iPad (John and I split up for the very last few trees) and the data weren't included with the data_entry_fix file. I will add that information to the final file tomorrow, with the 3/2/2022 dates.

**Comment by rudeboybert** [comment]
Hey @jess-shue I just merged PR #108. Note the following:

1. The CSV to take into the field field is data_entry_biannual_spr2022_BLANK_version_2.csv and it is ready to go. I sorted the stems by area then quadrat then tag. It has 495 rows i.e. we're still missing 5 but we know exactly which ones they are. 
2. Thanks for the heads up about the omission due to the 3rd iPad. I added a partial entry for 160910 to [data_entry_fix_2022.csv](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/raw_data/2022/data_entry_fix_2022.csv) in the last row just so I could update the field form. Please fill out the rest of the variables and reorder that row at your leisure.
3. Thanks again for linking [biannual_survey.R](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/Rscripts/survey_forms/biannual_survey.R). I had used that previously, but there are two stems in two quadrats that are split between two areas b/c they are split by the deer exclosure: 915 and 1113. I was wondering if there was something more precise based on lx and ly, but it seems not. I associated these two stems with area 3 (outside the exclosure); hopefully this ends up right.

**Comment by rudeboybert** [comment]
Closed by #114
